### ISSUE TITLE
add dashboard to track user count

### ISSUE THREAD

**Issue by pranav-kadam** [pranav-kadam/UserBasedScaling#2]

**Comment by siddharthkhedkar223** [comment]
Done with the dashboard , here is how it looks .....
This port shows metrics : ![Screenshot from 2024-10-23 10-47-46](https://github.com/user-attachments/assets/9abfd3af-cb81-46f8-929d-73b641846051)
This port uses those metrics and displays a dashboard :
![Screenshot from 2024-10-23 10-46-31](https://github.com/user-attachments/assets/7586dc66-5f5f-4ddc-952a-967100fe8598)
